file_object = open('dummy.txt', 'r')
type(file_object)
# help(file_object)
s = file_object.read()
print(s)
file_object.close()
new_file = open('my-new-file.txt', 'w')
new_file.write('Hello, this is my new file!')
new_file.close()
quit()
